Repository weni-ai/bothub-engine, pull requests merged in 2020-10, with the labels that each got.

#453 Feature/translator external
  bothub/api/v2/organization/views.py
  bothub/api/v2/repository/views.py
  bothub/api/v2/routers.py
  bothub/api/v2/translation/views.py
  bothub/api/v2/translator/__init__.py
  bothub/api/v2/translator/filters.py
  bothub/api/v2/translator/permissions.py
  bothub/api/v2/translator/serializers.py
  bothub/api/v2/translator/validators.py
  bothub/api/v2/translator/views.py
  bothub/authentication/authorization.py
  bothub/common/migrations/0092_merge_20200930_1819.py
  bothub/common/migrations/0093_repositorytranslator.py
  bothub/common/models.py
Labels: bug, enhancement

#454 Feature/translate automatically
  bothub/api/v2/nlp/views.py
  bothub/api/v2/repository/filters.py
  bothub/api/v2/repository/serializers.py
  bothub/api/v2/repository/views.py
  bothub/api/v2/translator/views.py
  bothub/common/migrations/0094_repositoryqueuetask_type_processing.py
  bothub/common/migrations/0095_auto_20201001_1944.py
  bothub/common/migrations/0096_auto_20201001_2005.py
  bothub/common/models.py
  bothub/common/tasks.py
Labels: enhancement

#456 Added case and for language translation
  bothub/api/v2/examples/filters.py
  bothub/api/v2/translator/filters.py
Labels: bug

#458 Added support pt_br for auto translation google
  bothub/common/languages.py
  bothub/common/tasks.py
Labels: enhancement

#459 Develop
  bothub/api/v2/examples/filters.py
  bothub/api/v2/translator/filters.py
  bothub/common/languages.py
  bothub/common/tasks.py
Labels: enhancement

#460 Score refact
  Pipfile.lock
  bothub/common/tasks.py
  bothub/utils.py
Labels: pendencies

#462 Added router repository train info
  bothub/api/v2/repository/serializers.py
  bothub/api/v2/repository/views.py
  bothub/api/v2/routers.py
  bothub/api/v2/tests/test_repository.py
Labels: enhancement, hacktoberfest-accepted

#464 Added filter search repositories by name, languages and categories
  bothub/api/v2/repository/views.py
Labels: enhancement, hacktoberfest-accepted

#465 Feature/migrate wit
  Pipfile.lock
  bothub/__init__.py
  bothub/api/v2/repository/permissions.py
  bothub/api/v2/repository/serializers.py
  bothub/api/v2/repository/views.py
  bothub/api/v2/routers.py
  bothub/common/__init__.py
  bothub/common/migrations/0097_repositorymigrate.py
  bothub/common/models.py
  bothub/common/tasks.py
  docker-compose.yml
Labels: enhancement, hacktoberfest-accepted

#466 Removed validation entities translation router
  bothub/api/v2/tests/test_translation.py
  bothub/api/v2/translation/serializers.py
  bothub/api/v2/translation/validators.py
Labels: enhancement, hacktoberfest-accepted

#457 Feature/scores
  .gitignore
  Pipfile
  Pipfile.lock
  bothub/api/v2/repository/serializers.py
  bothub/celery.py
  bothub/common/migrations/0097_repositoryscore.py
  bothub/common/migrations/0098_merge_20201008_1607.py
  bothub/common/models.py
  bothub/common/tasks.py
  bothub/utils.py
Labels: enhancement, hacktoberfest-accepted, help wanted

#471 replaced openssl-dev for libressl-dev to solve the apk package confli…
  Dockerfile
Labels: bug, hacktoberfest-accepted

#469 Feature/refact migration
  bothub/api/v2/repository/serializers.py
  bothub/common/migrate_classifiers/__init__.py
  bothub/common/migrate_classifiers/classifiers.py
  bothub/common/migrate_classifiers/wit/__init__.py
  bothub/common/migrate_classifiers/wit/type.py
  bothub/common/migrations/0097_repositoryscore.py
  bothub/common/migrations/0098_merge_20201008_1607.py
  bothub/common/migrations/0098_repositorymigrate_classifier.py
  bothub/common/migrations/0099_auto_20201008_1848.py
  bothub/common/migrations/0100_merge_20201009_1739.py
  bothub/common/models.py
  bothub/common/tasks.py
  bothub/settings.py
  bothub/utils.py
Labels: enhancement, hacktoberfest-accepted

#478 Added unique together Repository Reports
  bothub/common/migrations/0101_auto_20201020_1546.py
  bothub/common/models.py
Labels: bug, hacktoberfest-accepted

#477 fix/new_repository_info_keys
  bothub/api/v2/repository/serializers.py
  bothub/api/v2/tests/test_repository.py
Labels: enhancement

#484 Fix/repository train info
  bothub/api/v2/repository/serializers.py
Labels: enhancement

#479 Feature/word suggestion
  bothub/api/v2/examples/views.py
  bothub/api/v2/repository/serializers.py
  bothub/api/v2/repository/views.py
  bothub/common/tasks.py
  bothub/settings.py
  bothub/utils.py
Labels: enhancement, hacktoberfest-accepted
