Repository weni-ai/bothub-engine, pull requests merged in 2020-12, with the labels that each got.

#508 Feature/automatic evaluate
  bothub/api/v2/evaluate/filters.py
  bothub/api/v2/evaluate/serializers.py
  bothub/api/v2/nlp/views.py
  bothub/api/v2/repository/views.py
  bothub/api/v2/tests/test_evaluate.py
  bothub/api/v2/tests/test_repository.py
  bothub/common/migrations/0102_repositoryevaluateresult_cross_validation.py
  bothub/common/models.py
  bothub/common/tasks.py
Labels: enhancement

#513 Fix migrate function
  bothub/common/tasks.py
Labels: bug

#518 Enable documentation REDOC
  Pipfile
  Pipfile.lock
  bothub/api/v2/account/views.py
  bothub/api/v2/evaluate/views.py
  bothub/api/v2/examples/views.py
  bothub/api/v2/repository/views.py
  bothub/api/v2/swagger.py
  bothub/api/v2/translation/views.py
  bothub/settings.py
  bothub/urls.py
Labels: enhancement

#520 Feature/keycloak
  .dockerignore
  README.md
  bothub/api/v2/nlp/views.py
  bothub/api/v2/repository/serializers.py
  bothub/api/v2/repository/views.py
  bothub/api/v2/tests/test_evaluate.py
  bothub/api/v2/tests/test_repository.py
  bothub/api/v2/urls.py
  bothub/api/v2/views.py
  bothub/authentication/authorization.py
  bothub/common/migrations/0102_repositoryevaluateresult_cross_validation.py
  bothub/common/tasks.py
  bothub/settings.py
  bothub/utils.py
Labels: enhancement

#521 Fix NLP Authentication
  bothub/api/v2/nlp/views.py
  bothub/api/v2/repository/views.py
  bothub/api/v2/tests/test_nlp.py
  bothub/api/v2/views.py
  bothub/authentication/authorization.py
Labels: bug, enhancement

#522 Allow edit group name
  bothub/api/v2/groups/views.py
  bothub/api/v2/tests/test_groups.py
Labels: enhancement

#523 Added validation if there is already a phrase in the evaluate tests
  bothub/api/v2/evaluate/serializers.py
  bothub/api/v2/evaluate/validators.py
  bothub/api/v2/tests/test_evaluate.py
Labels: bug

#524 Added order by status result evaluate
  bothub/api/v2/evaluate/serializers.py
Labels: enhancement

#525 Added filter by confidence inbox
  bothub/api/v2/repository/filters.py
  bothub/api/v2/repository/views.py
Labels: enhancement
