Repository weni-ai/bothub-engine, pull requests merged in 2021-06, with the labels that each got.

#603 Added indexes models
  bothub/api/v2/repository/serializers.py
  bothub/common/migrations/0109_auto_20210601_0323.py
  bothub/common/migrations/0110_auto_20210601_1443.py
  bothub/common/models.py
Labels: bug

#607 Added repository_type to NewRepositoryViewSet endpoint
  bothub/api/v2/repository/serializers.py
Labels: enhancement

#609 Hotfix/train info
  bothub/api/v2/repository/permissions.py
  bothub/api/v2/repository/serializers.py
  bothub/api/v2/repository/views.py
  bothub/api/v2/tests/test_repository.py
  bothub/common/models.py
Labels: bug, enhancement

#608 Sending welcome to bothub is only sent when the account is created by the rest api
  bothub/api/v2/account/serializers.py
  bothub/authentication/models.py
  bothub/settings.py
Labels: bug, enhancement
